# Projeto Web Scraping

### Lendo uma tabela

In [6]:
import pandas as pd  # Importa a biblioteca pandas para manipulação de dados
import urllib3  # Importa a biblioteca urllib3 para fazer solicitações HTTP
from bs4 import BeautifulSoup  # Importa BeautifulSoup para analisar HTML

In [7]:
# Função responsável por fazer uma solicitação HTTP GET, utilizando a biblioteca urllib3
def faz_requisicao(site):
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning) # Desativa avisos de certificado não confiável
    manager = urllib3.PoolManager()  # Cria um gerenciador de pool HTTP
    return  manager.request("GET", site, headers={"User-Agent":"Mozilla/5.0"}) # Faz uma solicitação GET

# Faz a requisição HTTP para o 'site' e retorna um objeto BeautifulSoup para análise.
def le_site(site):
    response = faz_requisicao(site)  # Faz a requisição HTTP
    return BeautifulSoup(response.data, "html.parser") # Retorna um objeto BeautifulSoup

In [8]:
# Define a URL
url = "https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_riqueza_total"

In [9]:
# Define uma função para coletar dados de países e riqueza total
def func_le_paises():
    bs = le_site(url)  # Chama a função le_site para acessar o site
    table = bs.find("table", style="text-align: right")  # Procura por uma tabela com o estilo "text-align: right"
    if table is None:
        raise Exception("Tabela não encontrada")

    corpo = table.find("tbody")  # Encontra o corpo da tabela
    if corpo is None:
        raise Exception("Corpo não encontrado")
    
    itens = corpo.find_all("tr")  # Encontra todas as linhas da tabela

    paises = []  # Inicializa uma lista para armazenar os dados dos países
    for item in itens:
        dados = item.find_all("td")  # Encontra todas as células de dados da linha
        item_pais = []
        for dado in dados:
            item_pais.append(dado.text.replace('\xa0',''))  # Remove espaços em branco e adiciona os dados à lista

        if len(item_pais) > 0:
            paises.append(item_pais)  # Adiciona os dados do país à lista de países
    return paises

func_le_paises()   # Chama a função para coletar os dados dos países

[['—', 'Mundo', '317.084\n'],
 ['—', 'América do Norte', '106.513\n'],
 ['—', 'Ásia', '105.946\n'],
 ['1', 'Estados Unidos', '98.154\n'],
 ['—', 'Europa', '85.402\n'],
 ['2', 'China', '51.874\n'],
 ['3', 'Japão', '23.884\n'],
 ['4', 'Alemanha', '14.499\n'],
 ['5', 'Reino Unido', '14.209\n'],
 ['6', 'França', '13.883\n'],
 ['7', 'Itália', '10.569\n'],
 ['—', 'Oceania', '8.615\n'],
 ['8', 'Canadá', '8.319\n'],
 ['—', 'América Latina', '8.055\n'],
 ['9', 'Austrália', '7.577\n'],
 ['10', ' Espanha', '7.152\n'],
 ['11', ' Coreia do Sul', '7.107\n'],
 ['12', 'Índia', '5.972\n'],
 ['13', ' Taiwan[4]', '4.065\n'],
 ['14', ' Suíça', '3.611\n'],
 ['15', 'Países Baixos', '3.357\n'],
 ['16', 'Bélgica', '2.776\n'],
 ['—', 'África', '2.553\n'],
 ['17', 'Brasil', '2.464\n'],
 ['18', 'Rússia', '2.240\n'],
 ['19', 'Suécia', '1.920\n'],
 ['20', 'México', '1.729\n'],
 ['21', 'Áustria', '1.637\n'],
 ['22', 'Hong Kong[5]', '1.523\n'],
 ['23', ' Indonésia', '1.518\n'],
 ['24', ' Singapura', '1.289\n'],
 ['25', 'Dinamarca', '1.276\n'],
 ['26', 'Noruega', '1.181\n'],
 ['27', 'Nova Zelândia', '1.010\n'],
 ['28', 'Turquia', '1.010\n'],
 ['29', ' Arábia Saudita', '977\n'],
 ['30', 'Grécia', '975\n'],
 ['31', 'Polónia', '974\n'],
 ['32', 'Israel', '941\n'],
 ['33', 'Portugal', '916\n'],
 ['34', 'Chile', '819\n'],
 ['35', 'Irlanda', '806\n'],
 ['36', ' África do Sul', '786\n'],
 ['37', 'Finlândia', '697\n'],
 ['38', 'Emirados Árabes Unidos', '684\n'],
 ['39', 'Colômbia', '616\n'],
 ['40', 'Malásia', '598\n'],
 ['41', 'Tailândia', '525\n'],
 ['42', 'Chéquia', '524\n'],
 ['43', ' Filipinas', '518\n'],
 ['44', 'Peru', '467\n'],
 ['45', ' Paquistão', '422\n'],
 ['46', 'Argentina', '345\n'],
 ['47', ' Roménia', '317\n'],
 ['48', 'Vietname', '307\n'],
 ['49', 'Hungria', '294\n'],
 ['50', ' Kuwait', '278\n'],
 ['51', ' Irão', '272\n'],
 ['52', 'Iraque', '272\n'],
 ['53', 'Catar', '265\n'],
 ['54', 'Bangladesh', '240\n'],
 ['55', 'Marrocos', '216\n'],
 ['56', 'Líbia', '252\n'],
 ['57', 'Argélia', '241\n'],
 ['58', 'Egito', '212\n'],
 ['59', 'Luxemburgo', '188\n'],
 ['60', 'Eslováquia', '151\n'],
 ['61', ' Omã', '144\n'],
 ['62', ' Líbano', '140\n'],
 ['63', ' Nigéria', '139\n'],
 ['64', 'Islândia', '138\n'],
 ['65', 'Bulgária', '138\n'],
 ['66', 'Eslovênia', '133\n'],
 ['67', 'Croácia', '120\n'],
 ['68', 'Tunísia', '120\n'],
 ['69', ' Equador', '116\n'],
 ['70', ' Costa Rica', '111\n'],
 ['71', 'Angola', '102\n'],
 ['72', ' Uruguai', '97\n'],
 ['73', 'Chipre', '91\n'],
 ['74', ' Sri Lanka', '82\n'],
 ['75', 'Panamá', '77\n'],
 ['76', 'Sérvia', '73\n'],
 ['77', ' Jordânia', '72\n'],
 ['78', ' Cazaquistão', '62\n'],
 ['79', ' El Salvador', '61\n'],
 ['80', 'Estónia', '60\n'],
 ['81', ' Honduras', '58\n'],
 ['82', 'Quênia', '57\n'],
 ['83', 'Lituânia', '57\n'],
 ['84', 'Ucrânia', '55\n'],
 ['85', 'Letônia', '53\n'],
 ['86', ' Myanmar', '52\n'],
 ['87', 'Azerbaijão', '52\n'],
 ['88', 'Geórgia', '49\n'],
 ['89', 'Malta', '49\n'],
 ['90', 'Bolívia', '48\n'],
 ['91', 'Bahamas', '45\n'],
 ['92', 'Bósnia e Herzegovina', '40\n'],
 ['93', 'Paraguai', '38\n'],
 ['94', 'Albânia', '37\n'],
 ['95', ' Turquemenistão', '37\n'],
 ['96', ' Nepal', '35\n'],
 ['97', ' Ilhas Maurícias', '34\n'],
 ['98', ' Costa do Marfim', '34\n'],
 ['99', ' Camboja', '33\n'],
 ['100', ' Papua-Nova Guiné', '28\n']]

In [10]:
# Formatando a saída de dados em uma tabela com pandas.
data = pd.DataFrame(func_le_paises(), columns=["Posição", "País", "Riqueza Total por Bilhões (USD)"])
data.set_index("Posição") # Define a coluna "Posição" como índice da tabela

                      País Riqueza Total por Bilhões (USD)
Posição
—                    Mundo                       317.084\n
—         América do Norte                       106.513\n
—                     Ásia                       105.946\n
1           Estados Unidos                        98.154\n
—                   Europa                        85.402\n
...                    ...                             ...
96                   Nepal                            35\n
97         Ilhas Maurícias                            34\n
98         Costa do Marfim                            34\n
99                 Camboja                            33\n
100       Papua-Nova Guiné                            28\n

[107 rows x 2 columns]